### ISSUE TITLE
Unable to load environment variables from `.env.local`

### ISSUE THREAD

**Issue by kachar** [ilovepixelart/ts-migrate-mongoose#153]
**Describe the issue**
We're keeping our environment variables in file `.env.local` instead of `.env` and `ts-migrate-mongoose` is not picking them out of the box.

In order to load them we needed to manually invoke `dotenv`

```ts
// migrate.ts

import { config } from 'dotenv'

config({ path: '.env.local', override: true })

export default {
  uri: process.env.MIGRATE_MONGO_URI ?? 'mongodb://localhost:27017/test'
  // "collection": "migrations",
  // "migrationsPath": "./migrations",
  // "templatePath": "./migrations/template.ts",
  // "autosync": false
}
```

Do you plan to support similar functionality?

**Comment by ilovepixelart** [comment]
I like the Idea so short answer is yes)

**Comment by ilovepixelart** [comment]
PR: https://github.com/ilovepixelart/ts-migrate-mongoose/pull/154

**Comment by ilovepixelart** [comment]
Released in: https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v3.1.9
