### ISSUE TITLE
Importing `IOptions` interface externally

### ISSUE THREAD

**Issue by kachar** [ilovepixelart/ts-migrate-mongoose#155]
Thanks for the awesome lib! 🎉 

While running the project using `migrate.ts` strategy we noticed the following eslint rule warning:

> Assign object to a variable before exporting as module default eslint [import/no-anonymous-default-export](https://github.com/import-js/eslint-plugin-import/blob/v2.27.5/docs/rules/no-anonymous-default-export.md)

<img width="988" alt="image" src="https://github.com/ilovepixelart/ts-migrate-mongoose/assets/893608/0ea196de-9ae6-40d5-a1f9-4f890f9a7ff0">

While we can disable the rule locally we can also extract the config as a local variable and provide proper TS types for it.

**The interface:**

https://github.com/ilovepixelart/ts-migrate-mongoose/blob/d990b52edc27b14b3b9be20c1c4a96761bd8d598/src/interfaces/IOptions.ts#L1-L8

**Expected implementation:**

```ts
// migrate.ts
import type { IOptions } from 'ts-migrate-mongoose'

const migrateConfig: IOptions = {
  uri: "mongodb://localhost/my-db",
  collection: "migrations",
  migrationsPath: "./migrations",
  templatePath: "./migrations/template.ts",
  autosync: false,
}
export default migrateConfig
```

**Comment by ilovepixelart** [comment]
Yes I will make exports for it

**Comment by ilovepixelart** [comment]
PR: https://github.com/ilovepixelart/ts-migrate-mongoose/pull/156

**Comment by ilovepixelart** [comment]
Released in: https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v3.1.9

**Comment by ilovepixelart** [comment]
Released in: https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v3.1.9
