### ISSUE TITLE
prune not pruning the migrations

### ISSUE THREAD

**Issue by ellenschwartau** [ilovepixelart/ts-migrate-mongoose#177]
**Describe the bug**
Hey! Thank you for providing this library!
I just started evaluating your package for our use case and tried the prune command, which is not working as I expected.

**To Reproduce**

1. `yarn migrate create test-migration`
2. The migration file is created and also added to the new migrations collection in my database, status "down" (see screenshot below)
3. I wanted to remove it again by using: `yarn migrate prune` 
4. The comand runs without an error, but migration file and also the entry in the migrations collection is still there.

**Expected behavior**
Maybe my understanding of the prune command is wrong, but should't both, the migration file and also the entry in the migrations collections, be gone afterwards?

The detailed manual says something about options, I guess I need to define if it should be pruned from the db or from the database? What are the options to do so? :)

**Screenshots**
<img width="423" alt="image" src="https://github.com/ilovepixelart/ts-migrate-mongoose/assets/5683655/c8a8a31f-f663-41e0-a792-454c9bc8c5c4">

**Additional context**
I added a migrate.ts file with following settings:
```
export default {
  uri: process.env.MONGODB_CONNECTION_STRING,
  migrationsPath: './db/migrations',
  autosync: false,
};
```

Versions:
- yarn v1.22.19
- node v18.16.1
- ts-migrate-mongoose v3.3.0
- mongoose 6.10.5

**Comment by ilovepixelart** [comment]
Hello  @ellenschwartau, this is actually intended behavior

1. You need to delete migration file
2. Run prune command

Migrator will check FS migrations and will prune all entries in DB that are not present in FS

**Comment by ellenschwartau** [comment]
Ah allrighty, thank you!
