### ISSUE TITLE
Duplicate identifier

### ISSUE THREAD

**Issue by tipoc123** [ilovepixelart/ts-migrate-mongoose#226]
**Describe the bug**
`ts-migrate-mongoose` conflicts with package `mongoose`

**To Reproduce**

1. Use both `ts-migrate-mongoose` and `mongoose` packages (I have a `nestjs` project)

Lots of errors in the console like:

```
node_modules/ts-migrate-mongoose/node_modules/mongoose/types/virtuals.d.ts:11:10 - error TS2300: Duplicate identifier 'SchemaOptionsVirtualsPropertyType'.

11     type SchemaOptionsVirtualsPropertyType<DocType = any, VirtualPaths = Record<any, unknown>, TInstanceMethods = {}> = {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/mongoose/types/virtuals.d.ts:11:10
    11     type SchemaOptionsVirtualsPropertyType<DocType = any, VirtualPaths = Record<any, unknown>, TInstanceMethods = {}> = {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'SchemaOptionsVirtualsPropertyType' was also declared here.

```

**Expected behavior**
`ts-migrate-mongoose` works with the `mongoose` package

**Screenshots**
<img width="1480" alt="Снимок экрана 2023-11-10 в 06 26 45" src="https://github.com/ilovepixelart/ts-migrate-mongoose/assets/15922591/a6eb5499-0e0e-42d6-9ac9-f864f3e0b6f2">

**Desktop (please complete the following information):**

- OS: macOS Sonoma
- Version 14.1

**Additional context**
- mongoose 6.8.0
- ts-migrate-mongoose 3.4.2

**Comment by ilovepixelart** [comment]
Hello @tipoc123, ts-migrate-mongoose was designed to be used with mongoose
I tested your specific versions:

- mongoose 6.8.0
- ts-migrate-mongoose 3.4.2

Using my sample repo https://github.com/ilovepixelart/ts-express-swc and it's **not** compatibility issue between two versions

- It's either nest.js specific case
- Or your tsconfig.json is not setup properly

In either case I would like you to make a sample demo repo and share the link, so I can run and debug your case

**Comment by tipoc123** [comment]
I just installed the `ts-migrate-mongoose` package. Do I need additional steps?

**Comment by tipoc123** [comment]
My `tsconfig.json`:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2020",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "strictNullChecks": true,
    "noUncheckedIndexedAccess": true
  }
}

```

**Comment by ilovepixelart** [comment]
tsconfig.json looks good so it boils down to nest.js and your specific setup, try check https://github.com/ilovepixelart/ts-migrate-mongoose/tree/main/examples/programmatic-usage id you want to use ts-migrate-mongoose in programatic mode.

You need to add  .swcrc file only in case you use aliases in file references
Example:  import { someFunction} from '**@**/some/path.ts' as an example

**Comment by tipoc123** [comment]
> You need to add .swcrc file only in case you use aliases in file references Example: import { someFunction} from '**@**/some/path.ts' as an example

named imports or aliases?

alias (`as` keyword):

`import { foo as bar } from 'my-module'`

named import:

`import { foo } from 'my-module'`

**Comment by ilovepixelart** [comment]
In your tsconfig you don't have aliases/paths so you don't need yo use .swcrc
`
"paths": {
   "@/*": ["src/*"]
 }
`

**Comment by ilovepixelart** [comment]
Try making a sample project from scratch without (company or personal) code just nest.js and ts-migrate-mongoose, and same setup that you trying to make, and send me link I need full picture

**Comment by tipoc123** [comment]
I solved the problem using the same version of mongoose :)

**Comment by ilovepixelart** [comment]
If you use the same version of mongoose this will help you avoid interface name collision, but interesting to understand why you have it in the first place...

**Comment by ilovepixelart** [comment]
Example with nest: https://github.com/ilovepixelart/ts-express-nest
