### ISSUE TITLE
Possibly a problem with dynamic import

### ISSUE THREAD

**Issue by tipoc123** [ilovepixelart/ts-migrate-mongoose#228]
**Describe the bug**
Locally everything works well:

<img width="1634" alt="Снимок экрана 2023-11-22 в 06 37 25" src="https://github.com/ilovepixelart/ts-migrate-mongoose/assets/15922591/f051a518-50ad-45b9-8b5c-ef49737d7e06">

But it doesn’t work in kubernetes:

<img width="1840" alt="Снимок экрана 2023-11-22 в 06 33 18" src="https://github.com/ilovepixelart/ts-migrate-mongoose/assets/15922591/c85bd3a6-d805-4e1a-a481-7a8e8b888cb6">

According to logs it gets stuck on dynamic import:

https://github.com/ilovepixelart/ts-migrate-mongoose/blob/15173ae49248d217e6e88edfb079fc3de0ad80f6/src/migrator.ts#L411

 What could be the problem?

And what do empty curly braces (`{}`) at the end of logs mean?

**Additional context**
 - ts-migrate-mongoose 3.4.1

**Comment by tipoc123** [comment]
I even simplified the migration file to a single `console.log` call:

<img width="1840" alt="Снимок экрана 2023-11-22 в 07 11 53" src="https://github.com/ilovepixelart/ts-migrate-mongoose/assets/15922591/cd0ac2eb-80ce-41c0-b8f1-9d52797b9240">

**Comment by ilovepixelart** [comment]
This looks like SWC issue in relation to distro, my automated tests are running on `ubuntu-latest`
Which distro is used in your docker container?

**Comment by tipoc123** [comment]
`FROM node:18.12.1`

Is this information enough?

**Comment by ilovepixelart** [comment]
Made an example its working with your `node:18.12.1`
<img width="662" alt="image" src="https://github.com/ilovepixelart/ts-migrate-mongoose/assets/7249538/489fef69-1fbb-4412-b890-d7c4b1c05c10">
Check https://github.com/ilovepixelart/ts-express-swc/commit/7ce8578701139fdd255d1e175cfdd948e2aa5a52

**Comment by tipoc123** [comment]
@ilovepixelart Any other ideas what could be the problem?

**Comment by ilovepixelart** [comment]
<img width="667" alt="image" src="https://github.com/ilovepixelart/ts-migrate-mongoose/assets/7249538/cda11d9c-3d9d-4426-929b-df8f304cc456">
Same example with nets all works, I think it's your setup closing this issue
https://github.com/ilovepixelart/ts-express-nest

**Comment by tipoc123** [comment]
I wrapped the import in try-catch and this is the error in the logs:

```
/opt/nest-api/migrations/1699935100948-drop-orders.ts:1
import * as mongoose from 'mongoose';
^^^^^^
SyntaxError: Cannot use import statement outside a module
at Object.compileFunction (node:vm:360:18)
at wrapSafe (node:internal/modules/cjs/loader:1088:15)
at Module._compile (node:internal/modules/cjs/loader:1123:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
at Object.newLoader [as .ts] (/opt/nest-api/node_modules/pirates/lib/index.js:104:7)
at Module.load (node:internal/modules/cjs/loader:1037:32)
at Function.Module._load (node:internal/modules/cjs/loader:878:12)
at Module.require (node:internal/modules/cjs/loader:1061:19)
at require (node:internal/modules/cjs/helpers:103:18)
at /opt/nest-api/src/ts-migrate-mongoose/migrator.ts:519:28
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at Migrator.runMigrations (/opt/nest-api/src/ts-migrate-mongoose/migrator.ts:518:31)
at Migrator.run (/opt/nest-api/src/ts-migrate-mongoose/migrator.ts:209:27)
at runMigrations (/opt/nest-api/src/migrator.ts:45:3)
at AppBootstrap.bootstrap (/opt/nest-api/src/main.ts:118:5)
```

<img width="1840" alt="Снимок экрана 2023-12-14 в 00 47 01" src="https://github.com/ilovepixelart/ts-migrate-mongoose/assets/15922591/6c0a014d-3d66-4ea2-8e68-6fd798d316ba">

But it works locally.

Start of my migration file:

```
import * as mongoose from 'mongoose';
import * as process from 'process';

import { migratorLog } from '../src/migrator';

export async function up(): Promise<void> {
   ...
}
```
