### ISSUE TITLE
swcrc module type

### ISSUE THREAD

**Issue by tipoc123** [ilovepixelart/ts-migrate-mongoose#237]
**Describe the bug**
I can't use es6 imports in migration files in production (via kubernetes). But locally it works well.

I wrapped the dynamic import (`const migrationFunctions = (await import(migrationFilePath)) as IMigrationModule`) in try-catch and this is the error in the logs:

```
/opt/nest-api/migrations/1699935100948-drop-orders.ts:1
import * as mongoose from 'mongoose';
^^^^^^
SyntaxError: Cannot use import statement outside a module
at Object.compileFunction (node:vm:360:18)
at wrapSafe (node:internal/modules/cjs/loader:1088:15)
at Module._compile (node:internal/modules/cjs/loader:1123:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
at Object.newLoader [as .ts] (/opt/nest-api/node_modules/pirates/lib/index.js:104:7)
at Module.load (node:internal/modules/cjs/loader:1037:32)
at Function.Module._load (node:internal/modules/cjs/loader:878:12)
at Module.require (node:internal/modules/cjs/loader:1061:19)
at require (node:internal/modules/cjs/helpers:103:18)
at /opt/nest-api/src/ts-migrate-mongoose/migrator.ts:519:28
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at Migrator.runMigrations (/opt/nest-api/src/ts-migrate-mongoose/migrator.ts:518:31)
at Migrator.run (/opt/nest-api/src/ts-migrate-mongoose/migrator.ts:209:27)
at runMigrations (/opt/nest-api/src/migrator.ts:45:3)
at AppBootstrap.bootstrap (/opt/nest-api/src/main.ts:118:5)
```

Why are you using `type: 'commonjs'` and not `type: 'es6'` in `swcrc.ts`?

**Comment by ilovepixelart** [comment]
Hm, looks like the same topic again, provide some example that I can run and test, but previously es6 aka ESM were not supported I added it in latest release, so swcrc was defaulted to common js. We can patch that during build time for esm good point.

**Comment by ilovepixelart** [comment]
If that's the case this should help https://github.com/ilovepixelart/ts-migrate-mongoose/pull/239

**Comment by ilovepixelart** [comment]
Update to https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v3.5.4 and tell me if it works for you now

**Comment by tipoc123** [comment]
> Update to https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v3.5.4 and tell me if it works for you now

Still doesn't work. But I haven’t yet wrapped it in a `try-catch` block and looked at what error occurs.

**Comment by tipoc123** [comment]
If I want to use your sources directly in my project, do I just need to copy your `src` folder or do I need other files too?

**Comment by ilovepixelart** [comment]
Not sure what is your goal, but it's MIT licence you can do whatever

**Comment by tipoc123** [comment]
I have to use the sources directly to print the error that occurs during dynamic import. So I’m wondering if I need to copy additional files to myself besides those located in the `src` folder.

**Comment by ilovepixelart** [comment]
I encourage you to revisit this example: https://github.com/ilovepixelart/ts-express-nest, since I have no clue what is current setup on your side, this example contains docker, and all files you can follow, I tested it with latest release today works as expected. Regarding folders and copy of files I have no clue what you trying to do, read about `npm link` if you want to test you code against local package

**Comment by ilovepixelart** [comment]
In [v4.0.6](https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v4.0.6) ESM is now fully supported, give it a try.
