### ISSUE TITLE
compiling the migration file

### ISSUE THREAD

**Issue by tipoc123** [ilovepixelart/ts-migrate-mongoose#238]
Where is the migration `ts` files compiled? I only see `register(swcrc)` in your sources. At what stage does the compiler call occur?

**Comment by ilovepixelart** [comment]
It happens in memory its transpilation not compilation, so your migrations will be converted during actual run of migrator aka runtime

**Comment by tipoc123** [comment]
How does it understand which files to transpile and which not? I don't see any use of methods from the `@swcrc/core` package in your source code.

Or it automatically transpiles all dynamically imported files.

**Comment by ilovepixelart** [comment]
Automatically
