### ISSUE TITLE
commander.ts doesn't seem to pass the `connectOptions` forward

### ISSUE THREAD

**Issue by lagemanngui** [ilovepixelart/ts-migrate-mongoose#240]
**Describe the bug**
`commander.ts` doesn't seem to pass the `connectOptions` forward.

**To Reproduce**
1. Specify a connectOptions attribute in the `migrate.ts` 

```js
const connectOptions = {
  dbName: process.env.DB_NAME,
  tlsCAFile: 'global-bundle.pem',
};

export default {
  uri: process.env.DB_URI,
  collection: 'migrations',
  migrationsPath: './migrations',
  autosync: true,
  connectOptions,
};
```
2. Try to create a migration
3. It won't connect with the tlsCAFile specified;

**Expected behavior**
To connect using the provided tlsCAFile path.

**Additional context**
I'm using AWS Document DB and the tlsCAFile is mandatory to establish a connection.
I was able to get it to work doing the following:
```js
// commander.ts
// ...
const connectOptions = fileOptions.connectOptions;
// ...
const migratorOptions = {
        migrationsPath,
        uri,
        collection,
        autosync,
        connectOptions, // Added the connectOptions here
        cli: true
    };
```

**Comment by ilovepixelart** [comment]
Wow, good catch, will be fixed here https://github.com/ilovepixelart/ts-migrate-mongoose/pull/241

**Comment by ilovepixelart** [comment]
Released in: https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v3.5.5

**Comment by lagemanngui** [comment]
That was fast!
Thank you, sir. Cheers
