### ISSUE TITLE
Error on migrate up command

### ISSUE THREAD

**Issue by LuisPRamos** [ilovepixelart/ts-migrate-mongoose#26]
**Describe the bug**
Getting error `Cannot use import statement outside a module` when running the command `npx migrate up`.

**To Reproduce**
1. Create a new npm typescript project
2. Install ts-migrate-mongoose
3. Run commands `npx migrate create test` and `npx migrate up test`
4. See error text 
```
Synchronizing database with file system migrations...
Cannot use import statement outside a module
```

**Expected behavior**
Run the migration `test`'s up function code.

**Screenshots**
```
PS C:\test> npx migrate create test
Synchronizing database with file system migrations...
Created migration test in C:\test\migrations
Migration created. Run migrate up test to apply the migration
PS C:\test> npx migrate up test
Synchronizing database with file system migrations...
Cannot use import statement outside a module
```

**Desktop:**
 - OS: Windows 11 Home
 - Version 10.0.22621 Build 22621

**MongoDB:**
 - Device: Docker Kubernetes
 - Docker Image: mongo:4.0.23
 - Version: 4.0.23

**package.json**
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.1",
    "ts-migrate-mongoose": "^2.4.2"
  },
  "devDependencies": {
    "@types/express": "^4.17.1",
    "typescript": "^4.9.4"
  }
}
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es6",
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "dist"
  },
  "lib": ["es2015"]
}
```

**Comment by LuisPRamos** [comment]
Is there something I'm missing when using this package?

**Comment by ilovepixelart** [comment]
Hello @LuisPRamos thanks for the feedback, I was able to reproduce this issue, will try to fix it soon

**Comment by ilovepixelart** [comment]
@LuisPRamos update to version v2.4.3
