### ISSUE TITLE
v3.6.3 Client must be connected before running operations

### ISSUE THREAD

**Issue by zoulou00** [ilovepixelart/ts-migrate-mongoose#274]
Hello,

Since I installed v3.6.3 I got an error message when I run migrations against an Azure Cosmos DB for mongoDB:
 .I have two migrations to run. 
After the first one is up, I receive the error that say : "Client must be connected before running operations"
But when I am looking in the DB, the data are present.

I revert to v3.6.2.

<img width="640" alt="image" src="https://github.com/ilovepixelart/ts-migrate-mongoose/assets/36133851/6556e775-2d75-438f-a182-6588cb5c8190">

**Comment by ilovepixelart** [comment]
```TypeScrip
import mongoose from 'mongoose'
import mongooseOptions from '../options/mongoose'

import User from './User'

const getModels = async () => {
  // In case you using mongoose 6
  // https://mongoosejs.com/docs/guide.html#strictQuery
  mongoose.set('strictQuery', false)

  // Ensure connection is open so we can run migrations
  await mongoose.connect(process.env.MIGRATE_MONGO_URI ?? 'mongodb://localhost/my-db', mongooseOptions)

  // Return models that will be used in migration methods
  return {
    mongoose,
    User
  }
}

export default getModels
```
