### ISSUE TITLE
Support for the same database in multiple projects

### ISSUE THREAD

**Issue by lanz0519** [ilovepixelart/ts-migrate-mongoose#282]
**Is your feature request related to a problem? Please describe.**
Currently, when I use ts-migrate-mongoose in multiple projects to connect to the same database, the migrate files are distributed across different projects.
When I execute migrate up in project A, if there is a file in the database table that belongs to another project but has not been executed up, an error would occur, indicating that it cannot find the xxxxx file.

**Describe the solution you'd like**
The desired outcome is that the command execution is not interrupted regardless of the situation. Otherwise, I would need to specify different data tables in different projects, migrations-a and migrations-b. This would appear to be cumbersome.

**Additional context**
I hope my description is comprehensive enough. Can this functionality be supported?

**Comment by ilovepixelart** [comment]
Hm this is very strange setup, will be happy to hear more about it in detail.

I would assume now that use have multiple repos that represent individual project this means you can setup migration individually to each repo lets say they called Service A, Service B

In Service A: 
// Lets imagine you use .ts .json config in you first repo
```Json
{
  "uri": "mongodb://localhost/my-db",
  "migrationsPath": "migrations"
  "collection": "service-a"
}
```

In Service B
```Json
{
  "uri": "mongodb://localhost/my-db",
  "migrationsPath": "migrations"
  "collection": "service-b"
}

**Comment by ilovepixelart** [comment]
For monorepo you can setup migration once but provide path to configs I gave as example above
`-f, --config-path` and path to config service-a.json, service-b.json

**Comment by ilovepixelart** [comment]
There is also setup property for migration folder path you can use it in combination with schema prop, basically explore readme and try achieving with tools provided first and then we can reevaluate

**Comment by lanz0519** [comment]
In your example, "collection": "service-a" and "collection": "service-b" are my current solutions, but I think this would result in having multiple tables for different services, which may appear confusing.
I would like to have the collections for all services be the same, but ensure that the migration for each service does not affect each other.

**Comment by lanz0519** [comment]
When I initialize a project, I would like to use "migrate up" to handle all migrations in the directories at once. It would be cumbersome for me to specify the path one by one.
Can we refer to mongo-migrate here? I have just migrated from it.

**Comment by ilovepixelart** [comment]
I think it doesn't really matter how it's implemented somewhere else, still feels like a niche functionality for my project. Idea with db/fs sync is that always sure about your migration state and if you deleted file you must run prune command to resync

**Comment by lanz0519** [comment]
Alternatively, we should make sure that if a file is missing, it will not throw an error and interrupt the code execution.
