### ISSUE TITLE
Choose env.<local,dev,staging,prod>

### ISSUE THREAD

**Issue by FantinRaimbault** [ilovepixelart/ts-migrate-mongoose#290]
Hi, I want to be able to do 

NODE_ENV=production npx migrate up
NODE_ENV=dev npx migrate up
NODE_ENV=mycustomenv npx migrate up

You just have to do this :

```js
// in getMigrator function
+  if (process.env['NODE_ENV']) {
+    config({ path: `.env.${process.env['NODE_ENV']}`, override: true })
+  }
```

you can keep` config{ path : '.env' })` because its really usefull for default/shared variables

thx for the package, really helpful for me and my team <3

**Comment by ilovepixelart** [comment]
PR: https://github.com/ilovepixelart/ts-migrate-mongoose/pull/291

**Comment by ilovepixelart** [comment]
Released in: https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v3.7.0
