### ISSUE TITLE
Skip migrations files between specified one and those that have not been executed

### ISSUE THREAD

**Issue by FantinRaimbault** [ilovepixelart/ts-migrate-mongoose#299]
Hi, my problem is, when i use

`create up [migration name]`

it will perform all migrations between the targeted migration and those that have not been executed

I would like to be able to simply execute the targeted task, my team and I use your package to perform tasks that are not really migrations (edit/delete a column, delete a table etc ...) that's why we don't need to perform all the tasks in order.

**Describe alternatives you've considered**
maybe be able to do something like that ?

`npx migrate up foo --justOne=true`
or
`npx migrate up foo --skipBetween=true`

wdyt ?

thx dude, you did a great job with that package!

**Comment by ilovepixelart** [comment]
PR: https://github.com/ilovepixelart/ts-migrate-mongoose/pull/301

**Comment by ilovepixelart** [comment]
Released in: https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v3.8.0
