### ISSUE TITLE
Add updatedAt field

### ISSUE THREAD

**Issue by FantinRaimbault** [ilovepixelart/ts-migrate-mongoose#300]
Hi,
Can you add `updatedAt` field on the migration collection so we can know when this migration was executed?

**Comment by ilovepixelart** [comment]
PR: https://github.com/ilovepixelart/ts-migrate-mongoose/pull/301

**Comment by ilovepixelart** [comment]
Released in: https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v3.8.0
