### ISSUE TITLE
Use an existing Mongoose Connection

### ISSUE THREAD

**Issue by devilmark84** [ilovepixelart/ts-migrate-mongoose#305]
**Is your feature request related to a problem? Please describe.**
Is it possibile to pass an existing mongoose connection instead of a connection uri?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ilovepixelart** [comment]
It was done on purpose to unify / streamline process of working in CLI and Programmatic mode, basically you use same options / props in both modes
I might revisit this in the future but no plans for now
