### ISSUE TITLE
 bug on  Migrator.connect() default configuration invalid import "import(migrationFilePath)"

### ISSUE THREAD

**Issue by JasonThomasII** [ilovepixelart/ts-migrate-mongoose#306]
**Describe the bug**
When trying to run `Await Migrator.connect()`
with default values I get this error response

```
[!] (plugin commonjs--resolver) Error: invalid import "import(migrationFilePath)". It cannot be statically analyzed. Variable dynamic imports must start with ./ and be limited to a specific directory. For example: import(`./foo/${bar}.js`).

```
**To Reproduce**

set up Migrator with defualt configuration

```
      const migrator = await Migrator.connect({
        uri: `YOUR_MONGO_URI`,
      });
      ```

**Expected behavior**
Default values should create a connection for the migrator.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MAC OS 14.4.1

**Comment by ilovepixelart** [comment]
Hey @JasonThomasII can you fist check these samples
https://github.com/ilovepixelart/ts-express-swc using swc
https://github.com/ilovepixelart/ts-express-esbuild using esbuild

I think I need more context about your setup
If you using any other framework / bild system / bundler  you can create a small sample repo with your config so I can clone it and run locally to reproduce.

**Comment by JasonThomasII** [comment]
Hey @ilovepixelart,  sorry about letting this go stale. I got busy with other things wasn't wasn't able to reproduce the issue.
