### ISSUE TITLE
Create migration without saving in the db

### ISSUE THREAD

**Issue by talberkoMelio** [ilovepixelart/ts-migrate-mongoose#312]
I have multiple environments
When creating the migration file, I want it to be added to the repo, and in the CI I want to run it for the relevant environment.
How can I perform a create without passing the uri?

**Comment by ilovepixelart** [comment]
Setup environment modes

If mode is set, it will look for .env.[mode] file in the root of your project
For example, if MIGRATE_MODE=development it will look for .env.development file
If mode is not set, it will look for .env file in the root of your project

```bash
.env                # loaded in all cases
.env.local          # loaded in all cases (used as override for local development)
.env.[mode]         # only loaded in specified mode
.env.[mode].local   # only loaded in specified mode (used as override for local development)
```

**Comment by talberkoMelio** [comment]
@ilovepixelart the answer is not related to the question.
When performing a create it will try to connect to the db for saving the migration state.
I want to create the migration only in the repo. Running it should be after I commit the file and push, then in ci I want it to run the migration (then I already have the env and know how to config it).

The question is how to perform create without db connection?
