### ISSUE TITLE
.js extension in import statements throw error

### ISSUE THREAD

**Issue by APSLS** [ilovepixelart/ts-migrate-mongoose#324]
**Describe the bug**
When using file extension (.js) in import statements (as it is [required by node](https://nodejs.org/api/esm.html#terminology)) in project with ECMAScript modules, the migrate up command (`npx migrate up`) fails to find the module (for example: _Cannot find module '../models/index.js'_)

**To Reproduce**
- Unzip [learn-ts-migrate-mongoose.zip](https://github.com/user-attachments/files/16708802/learn-ts-migrate-mongoose.zip)
- `cd learn-ts-migrate-mongoose`
- `npm i`
- `npx migrate up`

**Expected behavior**
The expected error is 
```pwsh
Cannot find module '../models/index.js'
Require stack:
- C:\Users\me\Projects\learn-ts-migrate-mongoose\migrations\1673525773572-first-migration-demo.ts
- C:\Users\me\Projects\learn-ts-migrate-mongoose\node_modules\ts-migrate-mongoose\dist\cjs\migrator.js
- C:\Users\me\Projects\learn-ts-migrate-mongoose\node_modules\ts-migrate-mongoose\dist\cjs\commander.js
- C:\Users\me\Projects\learn-ts-migrate-mongoose\node_modules\ts-migrate-mongoose\dist\cjs\bin.js
```

**Desktop (please complete the following information):**
- OS Name:                   Microsoft Windows 10 Pro
- OS Version:                10.0.19045 N/A Build 19045

**Additional context**
The project README mentions that it supports _[x] Supports ESM and CommonJS_, so I tried it

**Comment by ilovepixelart** [comment]
This scope will display proper error when using ESM but full support of esm is not ready, will update the docs
Until register supports loading
https://github.com/ilovepixelart/ts-migrate-mongoose/pulls

**Comment by ilovepixelart** [comment]
In [v4.0.6](https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v4.0.6) ESM is now fully supported, give it a try.
