### ISSUE TITLE
Executable fails in latest version on windows

### ISSUE THREAD

**Issue by APSLS** [ilovepixelart/ts-migrate-mongoose#352]
**Describe the bug**

`npm run migrate -h` errors out and logs the following message
```powershell
Run arbitrary package scripts

Usage:
npm run-script <command> [-- <args>]

Options:
[-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]        
[-ws|--workspaces] [--include-workspace-root] [--if-present] [--ignore-scripts]
[--foreground-scripts] [--script-shell <script-shell>]

aliases: run, rum, urn

Run "npm help run-script" for more info
```

**To Reproduce**

1. Create empty folder and open powershell
2. `npm install ts-migrate-mongoose`
3. Create `.swcrc` as per README
4. Create migrate.ts as per README
5. Run `npm run migrate -h`

**Expected behavior**

Show the help message

**Screenshots**

![image](https://github.com/user-attachments/assets/3409cd4b-0375-41d6-a973-53e0644830d1)

**Desktop (please complete the following information):**

- OS: Microsoft Windows 10 Pro
- Browser Firefox
- OS Version: 10.0.19045 N/A Build 19045

**Additional context**

- It works in previous stable verison
- In the fix version, can the instructions to setup the codebase also be added. I'm having a hard time generating the binary to run

**Comment by ilovepixelart** [comment]
Hey my bad did a mistake in docs, run migrator like so `npx migrate -h`. Will update in new release

**Comment by ilovepixelart** [comment]
Docs updated in this pr: https://github.com/ilovepixelart/ts-migrate-mongoose/pull/353
