### ISSUE TITLE
ts-migrate-mongoose does not recognize `.js` files in production builds

### ISSUE THREAD

**Issue by d-tsaruk** [ilovepixelart/ts-migrate-mongoose#365]
#### **Description**
The `ts-migrate-mongoose` library is designed to manage MongoDB migrations, but it currently only works with `.ts` files. In production builds, where `.ts` files are transpiled into `.js`, the library fails to locate migration files due to its hardcoded `.ts` extension filter.

#### **Steps to Reproduce**
1. Create a migration file with a `.ts` extension (e.g., `1681234567890-create-users.ts`) in the migrations folder.
2. Run the application locally using `ts-node`. The migration works correctly.
3. Build the application (e.g., using `tsc`) and attempt to run it in production, where migration files are now `.js`.
4. The `ts-migrate-mongoose` library fails to detect the transpiled `.js` migration files.

#### **Expected Behavior**
`ts-migrate-mongoose` should recognize both `.ts` and `.js` files, allowing migrations to run seamlessly in both development and production environments.

#### **Actual Behavior**
The library only looks for `.ts` files due to the hardcoded filter:
```ts
.filter((filename) => /^\d{13,}-/.test(filename) && filename.endsWith('.ts'))
```

#### **Proposed Solution**
1. Update the file filter logic to support both `.ts` and `.js` extensions:
   ```ts
   .filter((filename) => /^\d{13,}-/.test(filename) && (filename.endsWith('.ts') || filename.endsWith('.js')))
   ```
2. Alternatively, dynamically determine the file extension based on the environment:
   ```ts
   const fileExtension = process.env.NODE_ENV === 'production' ? '.js' : '.ts';
   .filter((filename) => /^\d{13,}-/.test(filename) && filename.endsWith(fileExtension))
   ```

#### **Workaround**
As a temporary fix, migration files can be kept in `.ts` format in development and explicitly transpiled/copied as `.js` in production builds. However, this requires manual intervention and is prone to human error.

#### **Additional Context**
The issue arises during production deployment when using transpilers like TypeScript's `tsc`, which converts `.ts` files to `.js`. This problem limits the use of `ts-migrate-mongoose` in environments that rely on transpilation.

**Comment by d-tsaruk** [comment]
https://github.com/ilovepixelart/ts-migrate-mongoose/pull/366
My solution

**Comment by ilovepixelart** [comment]
Released in: https://github.com/ilovepixelart/ts-migrate-mongoose/releases/tag/v3.8.7
