### ISSUE TITLE
Can't use library with esbuild

### ISSUE THREAD

**Issue by SahaSaurav** [ilovepixelart/ts-migrate-mongoose#97]
**Describe the bug**
my project uses esbuild which seems to be incompatible with swc

**To Reproduce**
install ts-migrate-mongoose in project that builds with esbuild, run build step to see following errors:
<img width="441" alt="235848433-749ae402-2e8b-4b7b-bda5-fde379209de7" src="https://user-images.githubusercontent.com/32855889/235962720-540a9c59-0df3-4db6-a655-f254df4a58d7.png">

**Expected behavior**
Will this library not work with projects that use esbuild? Is there a workaround for this?

**Screenshots**

Desktop (please complete the following information):

OS: Windows 11
Let me know if any additional context is needed.

**Comment by ilovepixelart** [comment]
Duplicate of this: https://github.com/ilovepixelart/ts-migrate-mongoose/issues/98
