### ISSUE TITLE
Can't use library with esbuild 

### ISSUE THREAD

**Issue by SahaSaurav** [ilovepixelart/ts-migrate-mongoose#98]
**Describe the bug**
my project uses esbuild which seems to be incompatible with swc 

**To Reproduce**
install ts-express-swc in project that builds with esbuild, run build step to see following errors:
<img width="441" alt="esbuild_swc_issuepng" src="https://user-images.githubusercontent.com/32855889/235848433-749ae402-2e8b-4b7b-bda5-fde379209de7.png">

**Expected behavior**
Will this library not work with projects that use esbuild? Is there a workaround for this? 

**Desktop (please complete the following information):**
- OS: Windows 11

Let me know if any additional context is needed.

**Comment by ilovepixelart** [comment]
No issues I will transfer it here)

**Comment by SahaSaurav** [comment]
Hm this project builds without any issues

**Comment by SahaSaurav** [comment]
Seems that bundling is the issue, if I build ts-express-build with `esbuild --bundle --sourcemap --platform=node` I see errors in the screenshot. With bundling dependencies of dependencies will also be inlined, which is where the incompatibility of esbuild with swc becomes an issue.

**Comment by ilovepixelart** [comment]
Not sure why you actually need to bundle you backend code to be honest (I think transpiration wit source maps is enough), the only option you have then is to use flag to not bundle external packages by adding`--packages=external`

**Comment by SahaSaurav** [comment]
Yea seems that is the only option, thanks for the help!
