### ISSUE TITLE
Can't access models when running the package programmatically 

### ISSUE THREAD

**Issue by SahaSaurav** [ilovepixelart/ts-migrate-mongoose#99]
**Describe the bug**
The following from npm does not work for me:
<img width="574" alt="Screenshot 2023-05-03 112835" src="https://user-images.githubusercontent.com/32855889/236013139-3c0cdd32-3313-4607-a7d8-a4f6ffecc974.png">

I get the following error:
TypeError: Failed to run migration with name 'add-middle-name' due to an error. this is not a function

This is my code:
file using migrator
<img width="785" alt="Screenshot 2023-05-03 113922" src="https://user-images.githubusercontent.com/32855889/236013478-9b5d16a8-b12b-4f01-8291-9a8d4936be5e.png">

schema file
<img width="604" alt="Screenshot 2023-05-03 114008" src="https://user-images.githubusercontent.com/32855889/236013537-3b58911d-e0ff-4d0c-9268-e3ad705db755.png">

migration function
<img width="475" alt="Screenshot 2023-05-03 113827" src="https://user-images.githubusercontent.com/32855889/236013587-5746d50f-b90c-44dc-8b2e-5a46b9beb810.png">

**Expected behavior**
Should work as stated in npm.

**Comment by ilovepixelart** [comment]
Hey @SahaSaurav :) I think you reading someone else documentation
`ts-migrate-mongoose` does not have `this.` context
Follow this example: https://github.com/ilovepixelart/ts-migrate-mongoose#using-mongoose-models-in-your-migrations

**Comment by SahaSaurav** [comment]
Ah but its from your npm page - https://www.npmjs.com/package/ts-migrate-mongoose/v/2.2.0. No worries, I've found a work around.

**Comment by ilovepixelart** [comment]
Oh, you using old version I would not advise that)

**Comment by SahaSaurav** [comment]
Ah I had the wrong npm page but the right version *phew*

**Comment by ilovepixelart** [comment]
Yep in 2.2.0 I was using `ts-node` instead of `swc` so it might be better for bundling you tried to do in https://github.com/ilovepixelart/ts-migrate-mongoose/issues/98 but I would not recommend it

**Comment by SahaSaurav** [comment]
thanks for info, yea I'll definitely stick with the latest version :)
